### ISSUE TITLE
第一帧处理时就报错

### ISSUE THREAD

**Issue by zengliangjun** [MisEty/RTG-SLAM#3]
Depth Threshold (Close/Far Points): 2.98842
data/TUM_RGBD/rgbd_dataset_freiburg3_long_office_household [19/06 20:00:17]
cp: cannot stat 'data/TUM_RGBD/rgbd_dataset_freiburg3_long_office_household/points3d_depth.ply': No such file or directory
 [19/06 20:00:17]
========== curr frame is: 0 ========== [19/06 20:00:17]
 [19/06 20:00:17]
/opt/mambaforge/envs/agent_kit/lib/python3.10/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1695392020201/work/aten/src/ATen/native/TensorShape.cpp:3526.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
New map created with 897 points
[LOG] tracker cost time: 0.23026347160339355 [19/06 20:00:17]
Traceback (most recent call last):
  File "/workspace/VS2023/SLAM/GS3D/RTG-SLAM/slam.py", line 154, in <module>
    main()
  File "/workspace/VS2023/SLAM/GS3D/RTG-SLAM/slam.py", line 80, in main
    gaussian_map.mapping(curr_frame, frame_map, frame_id, optimization_params)
  File "/workspace/VS2023/SLAM/GS3D/RTG-SLAM/SLAM/multiprocess/mapper.py", line 99, in mapping
    self.gaussians_add(frame)
  File "/workspace/VS2023/SLAM/GS3D/RTG-SLAM/SLAM/multiprocess/mapper.py", line 132, in gaussians_add
    self.temp_to_optimize()
  File "/workspace/VS2023/SLAM/GS3D/RTG-SLAM/SLAM/multiprocess/mapper.py", line 884, in temp_to_optimize
    self.temp_pointcloud.update_geometry(
  File "/workspace/VS2023/SLAM/GS3D/RTG-SLAM/SLAM/gaussian_pointcloud.py", line 368, in update_geometry
    radius = self.get_radius
  File "/workspace/VS2023/SLAM/GS3D/RTG-SLAM/SLAM/gaussian_pointcloud.py", line 517, in get_radius
    min_length, _ = torch.min(scales, dim=1)
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

**Comment by zengliangjun** [comment]
你好，首先感谢能够开源你的代码！

第一帧处理时就异常，方便帮忙看一下。
谢谢！

**Comment by MisEty** [comment]
不清楚您的数据和配置文件是否正确，可以先用我们提供的配置文件测试能否正常运行。
如果您希望继续在您的设置下进行调试，这段报错可能是由于从深度图中采样点初始化高斯的过程中出现问题，您可以检查`sample_pixels`这个函数采样的点是否正常`。

**Comment by zengliangjun** [comment]
查到问题了， 是  Pillow 读深度图时将出现深度值为0的情况，包的版本有问题！
