### ISSUE TITLE
RuntimeError: No CUDA GPUs are available

### ISSUE THREAD

**Issue by ctl6998** [MisEty/RTG-SLAM#32]
I can not run with replica dataset

python slam.py --config ./configs/replica/office0.yaml

Traceback (most recent call last):
  File "/home/ctl6998/3D/RTG-SLAM/slam.py", line 13, in <module>
    from utils.camera_utils import loadCam
  File "/home/ctl6998/3D/RTG-SLAM/utils/camera_utils.py", line 15, in <module>
    from scene.cameras import Camera
  File "/home/ctl6998/3D/RTG-SLAM/scene/__init__.py", line 13, in <module>
    from scene.dataset_readers import sceneLoadTypeCallbacks
  File "/home/ctl6998/3D/RTG-SLAM/scene/dataset_readers.py", line 34, in <module>
    from scene.gaussian_model import BasicPointCloud
  File "/home/ctl6998/3D/RTG-SLAM/scene/gaussian_model.py", line 20, in <module>
    from utils.general_utils import (
  File "/home/ctl6998/3D/RTG-SLAM/utils/general_utils.py", line 22, in <module>
    float_dev = torch.tensor([0], device="cuda", dtype=torch.float32)
  File "/home/ctl6998/miniconda3/envs/RTG-SLAM/lib/python3.9/site-packages/torch/cuda/__init__.py", line 229, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available

**Comment by MisEty** [comment]
You can first test whether PyTorch can correctly use CUDA tensors.

**Comment by Leven-Cheung** [comment]
hi, i have already test that PyTorch can correctly use CUDA tensors.But this issue still happen. 

Python 3.9.20 | packaged by conda-forge | (main, Sep 30 2024, 17:49:10)
[GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.cuda.is_available())
True
>>> print(torch.version.cuda)
11.7
>>> print(torch.cuda.get_device_name(0))
NVIDIA GeForce RTX 3090
>>> exit()

**Comment by atat1010** [comment]
> hi, i have already test that PyTorch can correctly use CUDA tensors.But this issue still happen.
> 
> Python 3.9.20 | packaged by conda-forge | (main, Sep 30 2024, 17:49:10) [GCC 13.3.0] on linux Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > import torch
> > > > print(torch.cuda.is_available())
> > > > True
> > > > print(torch.version.cuda)
> > > > 11.7
> > > > print(torch.cuda.get_device_name(0))
> > > > NVIDIA GeForce RTX 3090
> > > > exit()

Hello, have you solved this problem?
