### ISSUE TITLE
RuntimeError: Pickling of "orbslam2.System" instances is not enabled

### ISSUE THREAD

**Issue by huarzail** [MisEty/RTG-SLAM#43]
When I run the Single Process: python slam.py --config ./configs/replica/office0.yaml，the running is OK. 
But when I run the Multi Process: python slam_mp.py --config ./configs/replica/office0.yaml. There some errors for me, The error logs is :

Traceback (most recent call last):
  File "/home/gvlib_ljh/3DGS-SLAM/RTG-SLAM/slam_mp.py", line 58, in <module>
    main()
  File "/home/gvlib_ljh/3DGS-SLAM/RTG-SLAM/slam_mp.py", line 54, in main
    slam.run()
  File "/home/gvlib_ljh/3DGS-SLAM/RTG-SLAM/SLAM/multiprocess/system.py", line 69, in run
    p.start()
  File "/home/gvlib_ljh/micromamba/envs/RTG-SLAM/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/gvlib_ljh/micromamba/envs/RTG-SLAM/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/gvlib_ljh/micromamba/envs/RTG-SLAM/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/home/gvlib_ljh/micromamba/envs/RTG-SLAM/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/gvlib_ljh/micromamba/envs/RTG-SLAM/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/gvlib_ljh/micromamba/envs/RTG-SLAM/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/gvlib_ljh/micromamba/envs/RTG-SLAM/lib/python3.10/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
RuntimeError: Pickling of "orbslam2.System" instances is not enabled (http://www.boost.org/libs/python/doc/v2/pickle.html)
[W CudaIPCTypes.cpp:16] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]

**Comment by DDDontbenoob** [comment]
I have the same problem....

**Comment by DDDontbenoob** [comment]
slam_mp.py文件中记得把args.mode 改成 "multi process"，这样就可以了，主进程中的orbslam2.System对象无法序列化传递给子进程，所以要在子进程内部初始化对象

**Comment by Justzhongjj** [comment]
@DDDontbenoob 请问具体是修改哪一行，怎么修改呢
